version: "3.4"

services:
  myshare_notifications:
    container_name: myshare_notifications
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    entrypoint: ["air"]
    ports:
      - "3030:3030"
    volumes:
      - ~/.cache/go-build:/root/.cache/go-build
      - ./src:/app/src
      - ./certs:/certs
    env_file: .env
    environment:
      PORT: 3030
      SERVER_HOST: https://myshare-telegram.dev:3030
      FIRESTORE_EMULATOR_HOST: firebase:8080

  firebase:
    image: spine3/firebase-emulator
    ports:
      - "4000:4000"
      - "8080:8080"
      - "41339:41339"
    environment:
      FIRESTORE_EMULATOR_PORT: 8080
      UI_EMULATOR_PORT: 4000
      GCP_PROJECT: myshare-notifications-local
